config/routes.rb
Rails.application.routes.draw do
  
  
  resources :comments
  get 'user/show'

  get 'votes/new'

  get 'votes/create'

  get 'votes/destroy'

  resources :votes
  devise_for :users
  resources :user do
    post 'show_favorites', on: :member
    post 'show_comments', on: :member
    post 'show_votes', on: :member
  end
  resources :restaurants do
  	post 'upvote', on: :member
  	post 'downvote', on: :member
    post 'add_comment'
  end

  root 'restaurants#home', as: 'home_index'

  #root 'home#index', as: 'home_index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :restaurant
	belongs_to :user

	scope :for_restaurants, ->(_restaurant_id) {where(restaurant_id: _restaurant_id).order(created_at: :desc)}
	scope :for_user, ->(_user_id) {where(user_id: _user_id)}

	# Get all comments from a single user for a given restaurant
	def self.getUserCommentsPerRestaurant(restaurant_id, user_id)
		Comment.for_restaurants(restaurant_id).for_user(user_id)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:create, :index, :show]
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    if current_user
      @comment = Comment.new(comment_params)
    
      respond_to do |format|
        if @comment.save
          format.html { }
          format.js {render inline: "location.reload();" }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to new_user_session_url, notice: 'Please sign in to comment.' }
        format.js { }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :restaurant_id, :user_comment)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :comment_user_id %>
  </div>

  <div class="field">
    <%= form.label :restaurant_id %>
    <%= form.number_field :restaurant_id, id: :comment_restaurant_id %>
  </div>

  <div class="field">
    <%= form.label :user_comment %>
    <%= form.text_area :user_comment, id: :comment_user_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Restaurant</th>
      <th>User comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.restaurant_id %></td>
        <td><%= comment.user_comment %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @comment.restaurant_id %>
</p>

<p>
  <strong>User comment:</strong>
  <%= @comment.user_comment %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>