config/routes.rb
Rails.application.routes.draw do
  
  
  resources :comments
  get 'user/show'

  get 'votes/new'

  get 'votes/create'

  get 'votes/destroy'

  resources :votes
  devise_for :users
  resources :user do
    post 'show_favorites', on: :member
    post 'show_comments', on: :member
    post 'show_votes', on: :member
  end
  resources :restaurants do
  	post 'upvote', on: :member
  	post 'downvote', on: :member
    post 'add_comment'
  end

  root 'restaurants#home', as: 'home_index'

  #root 'home#index', as: 'home_index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :restaurants
  has_many :votes
  has_many :comments

  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def show_votes
  	@restaurants = Restaurant.getUserVotesForAllRestaurants(current_user.id)
  	respond_to do |format|
      format.html { render 'new' }
      format.js   { render layout: false }
    end
  end

  def show_favorites
  	@restaurants = Restaurant.upvoted(current_user.id);
  	respond_to do |format|
      format.html { render 'new' }
      format.js   { render layout: false }
    end
  end

  def show_comments
  	@restaurants = Restaurant.getUserCommentedRestaurants(current_user.id)
  	#@comments = Comment.getUserComments(current_user.id)

  	respond_to do |format|
      format.html { render 'new' }
      format.js   { render layout: false }
    end
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_show_comments.html.erb
<h2>Comments you've made:</h2>

<% @restaurants.each do |restaurant| %>
	<div class="commented-restaurants">
		<div class="rest-name">
			<%= link_to restaurant.name, restaurant_path(restaurant.id) %>
		</div>
		<%= render('user_comments', comments: Comment.getUserCommentsPerRestaurant(restaurant.id, current_user.id)) %>
	</div>
<% end %>

app/views/user/_show_favorites.html.erb
<h2>Restaurants you've voted on:</h2>

<% restaurants.each do |restaurant| %>
	<%= render('restaurants/restaurant', restaurant: restaurant) %>
<% end %>

app/views/user/_show_votes.html.erb
<h2>Restaurants you've voted on:</h2>

<% restaurants.each do |restaurant| %>
	<%= render('restaurants/restaurant', restaurant: restaurant) %>
<% end %>

app/views/user/_user_comments.html.erb

<% comments.each do |comment| %>
<div class="comment">
	<div class="comment-date">
		<%= comment.created_at.strftime("%B %m, %Y") %>
	</div>
	<div class="user-comment">
		<%= comment.user_comment %>
	</div>
</div>
<div class="clear"></div>
<% end %>

app/views/user/show.html.erb
<h1>
	Hello <%= current_user.email %>

	<%= link_to "Edit Account", edit_user_registration_path(current_user.id), class: "acc_edit" %>
</h1>
<div class="view-select-section">
<%= button_to 'View My Votes', show_votes_user_path(current_user), :remote => true, class: "view-select" %>

<%= button_to 'View My Comments', show_comments_user_path(current_user), :remote => true, class: "view-select" %>

<%= button_to 'View My Favorites', show_favorites_user_path(current_user), :remote => true, class: "view-select" %>
</div>
<div id="selection">

</div>

app/views/user/show_comments.js.erb
$("#selection").html("<%= escape_javascript render(:partial => 'show_comments', :locals => { :restaurants => @restaurants }) %>");

app/views/user/show_favorites.js.erb
$("#selection").html("<%= escape_javascript render(:partial => 'show_favorites', :locals => { :restaurants => @restaurants }) %>");

app/views/user/show_votes.js.erb
$("#selection").html("<%= escape_javascript render(:partial => 'show_votes', :locals => { :restaurants => @restaurants }) %>");