config/routes.rb
Rails.application.routes.draw do
  
  
  resources :comments
  get 'user/show'

  get 'votes/new'

  get 'votes/create'

  get 'votes/destroy'

  resources :votes
  devise_for :users
  resources :user do
    post 'show_favorites', on: :member
    post 'show_comments', on: :member
    post 'show_votes', on: :member
  end
  resources :restaurants do
  	post 'upvote', on: :member
  	post 'downvote', on: :member
    post 'add_comment'
  end

  root 'restaurants#home', as: 'home_index'

  #root 'home#index', as: 'home_index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	belongs_to :user, optional: true
	has_many :votes
	has_many :comments

	scope :user_votes, -> {
		joins("left join votes 
			on restaurants.id = votes.restaurant_id").where("votes.id is not null")
	}
	scope :user_comments, -> (_user_id) { joins(:comments).where("comments.user_id = ?", _user_id) }
	scope :upvoted, -> (_user_id) { joins(:votes).where("votes.user_id = ? and votes.vote = 1", _user_id).sort_by(&:getVotes).reverse }

	# Search by restaurant name or city
	# or return all restaurants if none match the search
	def self.search(name, city)
		if name != "" && city != ""
			where("name like ? AND city like ?", "%#{name}%", city)
		elsif name && city == ""
			where("name like ?", "%#{name}%")
		elsif city && name == ""
			where("city = ?", city)
		elsif city == "" && city == ""
			Restaurants.all
		end
	end

	# Get total of all votes for a restaurant
	# Adding one for an upvote and subtracting one for a downvote
	def getVotes
		#@restaurant_votes = Restaurant.where("restaurant_id = ?", self.id).joins(:votes)
		@restaurant_votes = Vote.for_restaurants(self)
		@vote_total = 0
		if !@restaurant_votes.empty?
			@restaurant_votes.each do |vote|
				@vote_total = @vote_total + vote.vote
			end
		else
			@vote_total = 0
		end
		return @vote_total
	end

	# Check whether a user has voted on a restaurant
	def checkForUserVote(user_id)
		@user_vote = Vote.for_user(user_id).for_restaurants(self)
	end

	# Sort list of restaurant votes for user from higest to lowest
	def self.sortByVotes
		Restaurant.all.sort_by(&:getVotes).reverse
	end

	# Get restaurants that a given user has voted on
	# Sorted from highest to lowest
	def self.getUserVotesForAllRestaurants(user_id)
		@user_restaurants = Restaurant.user_votes.where("votes.user_id = ?", user_id).sort_by(&:getVotes).reverse
	end

	# Get count of all comments on a given restaurant
	def self.getNumberOfCommentsForRestaurant(restaurant_id)
		@comment_count = Comment.for_restaurants(restaurant_id).count
	end

	# Get all comments for a single restaurant
	def getComments
		Comment.for_restaurants(self.id)
	end

	# Get comments on all restaurants for a given user
	def self.getUserCommentedRestaurants(user_id)
		Restaurant.user_comments(user_id).uniq
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:home, :index, :show, :upvote, :downvote]
  # before_action { flash.discard }

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.search(params[:name], params[:city]).sortByVotes
    @results = false

    if @restaurants.present?
      #@restaurants = @restaurants.order(getVotes :desc)
      @results = true
    else
      @restaurants = Restaurant.all
    end
  end

  def home
    @restaurants = Restaurant.sortByVotes
    
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @comments = @restaurant.getComments
    @comment_user = @comments.joins("inner join users on 
                      comments.id = users.id")
  end

  # GET /restaurants/new
  def new
    @restaurant = current_user.restaurants.build
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = current_user.restaurants.build(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    if current_user
      @restaurant = Restaurant.find(params[:id])
      @user_vote = @restaurant.checkForUserVote(current_user.id)
      if @user_vote.count != 0
        @vote = @user_vote.first.vote
      end

      if @user_vote.count < 1
        @vote = Vote.create!(user_id: current_user.id, restaurant_id: @restaurant.id, vote: 1)
      elsif @user_vote.first.vote == -1
        Vote.destroy(@user_vote.first.id)
        @vote = Vote.create!(user_id: current_user.id, restaurant_id: @restaurant.id, vote: 1)
      else
        @vote = 1
        Vote.destroy(@user_vote.first.id)
      end
      respond_to do |format|
        format.html { render 'new' }
        format.js   { render layout: false }
      end
    else
      respond_to do |format|
        format.js   { flash.now[:notice] = "Please sign in to vote." }
      end
    end    
  end

  def downvote
    if current_user
      @restaurant = Restaurant.find(params[:id])
      @user_vote = @restaurant.checkForUserVote(current_user.id)
      if @user_vote.count != 0
        @vote = @user_vote.first.vote
      end

      if @user_vote.count < 1
        @vote = Vote.create!(user_id: current_user.id, restaurant_id: @restaurant.id, vote: -1)
      elsif @user_vote.first.vote == 1
        Vote.destroy(@user_vote.first.id)
        @vote = Vote.create!(user_id: current_user.id, restaurant_id: @restaurant.id, vote: -1)
      else
        @vote = -1
        Vote.destroy(@user_vote.first.id)
      end
      respond_to do |format|
        format.html { render 'new' }
        format.js   { render layout: false }
      end
    else
      respond_to do |format|
        format.js   { flash.now[:notice] = "Please sign in to vote." }
      end
    end    
  end

  def add_comment 
    @comment = Comment.new
    respond_to do |format|
      format.html { render 'new' }
      format.js   { render layout: false }
    end
  end

  #def getComments(restaurant_id)
  #  @comments = Comment.getComments(restaurant_id)
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :city, :state, :zip, :restauranttype, :pricepoint, :user)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_comments.html.erb
<% @comments.each do |comment| %>
  <div class="comments">
      <div class="show-user">
        <%= User.where(id: comment.user_id).first.email %>
        <span class="date"><%= comment.created_at.strftime("%B %m, %Y") %></span>
      </div>
      <div class="show-comment">
        <%= comment.user_comment %>
      </div>
      <div class="clear"></div>
  </div>
<% end %>

app/views/restaurants/_downvote.html.erb
<% if current_user %>
	<% user_vote = restaurant.checkForUserVote(current_user.id) %>
	<% if user_vote.count > 0 %>
		<% @vote = user_vote.first.vote %>
	<% else %>
		<% @vote = 0 %>
	<% end %>
<% end %>

<% if @vote == -1 %>
	<%= button_to downvote_restaurant_path(restaurant), class: 'clicked', :remote => true do %>
			<%= fa_icon "thumbs-down" %>
	<% end %>
<% else %>
	<%= button_to downvote_restaurant_path(restaurant), :remote => true do %>
			<%= fa_icon "thumbs-down" %>
	<% end %>
<% end %>
</td>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :restaurant_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :restaurant_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :restaurant_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :restaurant_state %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip, id: :restaurant_zip %>
  </div>

  <div class="field">
    <%= form.label "Type" %>
    <%= form.text_field :restauranttype, id: :restaurant_restauranttype %>
  </div>

  <div class="field">
    <%= form.label "Price Point" %>
    <%= form.number_field :pricepoint, id: :restaurant_pricepoint %>
  </div>
  
  <div class="clear"></div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div id="row_<%= restaurant.id %>" class="restaurant">
        <% if restaurant.pricepoint == 1 %>
          <%= image_tag 'burger.jpeg' %>
        <% elsif restaurant.pricepoint == 2 %>
          <%= image_tag 'white-tablecloth.jpeg' %>
        <% else %>
          <%= image_tag 'fine-dining.jpeg' %>
        <% end %>
          <h2><%= link_to restaurant.name, restaurant_path(restaurant.id) %></h2>

          <%= restaurant.restauranttype %>
                &mdash;
          <%= "$" * restaurant.pricepoint %>

          <div class="down">
            <%= render('restaurants/downvote', restaurant: restaurant) %>
          </div>

          <div class="votes">
            <%= render('restaurants/votes', restaurant: restaurant) %>
          </div>

          <div class="upvs">
            <%= render('restaurants/upvote', restaurant: restaurant) %>
          </div> 

          <div class="comments-icon">
            <%= fa_icon "comment" %>
            <%= Restaurant.getNumberOfCommentsForRestaurant(restaurant.id) %>
          </div>

          <br />
          <div class="address">
            <%= restaurant.address %> <br />
            <%= restaurant.city %> <br />
            <%= restaurant.state + ", " + restaurant.zip %>
          </div>
        
      </div>
      <div class="clear"></div>

app/views/restaurants/_upvote.html.erb
<% if current_user %>
	<% user_vote = restaurant.checkForUserVote(current_user.id) %>
	<% if user_vote.count > 0 %>
		<% @vote = user_vote.first.vote %>
	<% else %>
		<% @vote = 0 %>
	<% end %>
<% end %>

<% if @vote == 1 %>
	<%= button_to upvote_restaurant_path(restaurant), class: 'clicked', :remote => true do %>
		<%= fa_icon "thumbs-up" %>
	<% end %>
<% else %>
	<%= button_to upvote_restaurant_path(restaurant), :remote => true do %>
		<%= fa_icon "thumbs-up" %>
	<% end %>
<% end %>

app/views/restaurants/_votes.html.erb
<%= restaurant.getVotes %>

app/views/restaurants/downvote.js.erb
<% if current_user %>
	$("#row_<%= @restaurant.id %> .votes").html("<%= escape_javascript render(:partial => 'votes', :locals => { :restaurant => @restaurant }) %>");
	<% if @vote == nil %>
    $("#row_<%= @restaurant.id %> .down button").addClass("clicked");
  <% elsif @vote == -1 %>
	$("#row_<%= @restaurant.id %> .down button").removeClass("clicked");
  <% else %>
    $("#row_<%= @restaurant.id %> .down button").addClass("clicked");
    $("#row_<%= @restaurant.id %> .upvs button").removeClass("clicked");
  <% end %>
<% else %>
	$(".notice").html("<%= flash[:notice] %>");
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/home.html.erb
<div class="restaurant-list">
	<h1>Top Restaurants</h1>
	
		<% @restaurants.each do |restaurant| %>
		  <%= render('restaurant', restaurant: restaurant) %>
		<% end %>


</div>


app/views/restaurants/index.html.erb
<h1>Search Results</h1>

<% if @results == false %>
 
  <div class="results">
    <p>No search results found.  Check out these other great restaurants!</p>
  </div>

<% end %>

<% @restaurants.each do |restaurant| %>
    <%= render('restaurant', restaurant: restaurant) %>
<% end %>

app/views/restaurants/new.html.erb
<h2>New Restaurant</h2>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', request.referer.present? ? request.referer : home_index_url  %>

app/views/restaurants/show.html.erb
<div class="show-restaurant">
  <%= render('restaurant', restaurant: @restaurant) %>
  
  <%= form_for(Comment.new, :remote => true, class: "comment-form") do |f|  %>
    Comment: <%= f.text_area :user_comment, cols: 50, rows: 10, class: 'comment-box' %>
    <% if (current_user) %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
    <% end %>
    <%= f.hidden_field :restaurant_id, :value => @restaurant.id %>
    <%= f.submit 'Add Comment' %>
  <% end %>
</div>
        <div id="comment-area">
          <%= render('comments', comments: @comments) %>
        </div>

<%= link_to 'Back', request.referer.present? ? request.referer : home_index_url  %>

app/views/restaurants/upvote.js.erb
<% if current_user %>
  $("#row_<%= @restaurant.id %> .votes").html("<%= escape_javascript render(:partial => 'votes', :locals => { :restaurant => @restaurant }) %>");
  <% if @vote == nil %>
    $("#row_<%= @restaurant.id %> .upvs button").addClass("clicked");
  <% elsif @vote == 1 %>
	$("#row_<%= @restaurant.id %> .upvs button").removeClass("clicked");
  <% else %>
    $("#row_<%= @restaurant.id %> .upvs button").addClass("clicked");
    $("#row_<%= @restaurant.id %> .down button").removeClass("clicked");
  <% end %>
<% else %>
	$(".notice").html("<%= flash[:notice] %>");
<% end %>