config/routes.rb
Rails.application.routes.draw do
  
  
  resources :comments
  get 'user/show'

  get 'votes/new'

  get 'votes/create'

  get 'votes/destroy'

  resources :votes
  devise_for :users
  resources :user do
    post 'show_favorites', on: :member
    post 'show_comments', on: :member
    post 'show_votes', on: :member
  end
  resources :restaurants do
  	post 'upvote', on: :member
  	post 'downvote', on: :member
    post 'add_comment'
  end

  root 'restaurants#home', as: 'home_index'

  #root 'home#index', as: 'home_index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SplitTheCheck</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
	<link href="https://fonts.googleapis.com/css?family=Lobster|Roboto" rel="stylesheet">
	
	
  </head>
  
  <body>
	<header class="logo">
		<h1 class="icon"><%= fa_icon "copy" %></h1><h1>Split the Check</h1>
	
		<ul class="nav">
			<li><a href="/">Home</a></li>
			<li><a href="/restaurants/new">Add a Restaurant</a></li>
			<div class="user_options">
			<% if current_user %>
				<li>
					<%= link_to current_user.email, user_show_path %>
				<li>
					<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
				</li>
			<% else %>
				<li>
					<%= link_to "Register", new_user_registration_path %>
				</li>
				<li>
					<%= link_to "Sign In", new_user_session_path %>
				</li>
			<% end %>
		</div>
		</ul>
	</header>
	<div class="form-holder">
		<div class="search">
		<!-- <form class="search"> -->
		<h2>Search for a Restaurant</h2>

		<%= form_tag restaurants_path, method: :get do %>
			<%= label_tag 'name' %>
			<%= text_field_tag :name, params[:name] %>
			<%= label_tag 'City' %>
			<%= text_field_tag :city, params[:city] %>
			<%= submit_tag "Search", :name => nil, :city => nil %>
		<% end %>
		</div>
	</div>

	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

	<div id="wrapper">
	  <main class="<%= controller.controller_name %>">
			<%= yield %>
	  </main>
	</div>
	  <footer>
	  	<span class="copyright">&copy;2018 Mandi Matchett</span>
	  </footer>
  </body>
</html>